### ISSUE TITLE
Reference errors. Does not compile.

### ISSUE THREAD

**Issue by kovacev** [rischwa/eve-plh#2]
Lots of reference errors. Atleast half of the references fail to load.

**Comment by rischwa** [comment]
did you restore the nuget packages for the solution?

**Comment by kovacev** [comment]
Started from clean state again. this is the result.

**EVE Killboard Analyser (20 References)**
![image](https://user-images.githubusercontent.com/5053207/32697516-0e25827a-c7e2-11e7-802c-e1e041d44da7.png)

**Eve Local Chat Analyser (1 Reference)**
System.Net.Http

**GraphX.Controls (2 References)**
QuickGraph
YAXLib

**GraphX.Logic (2 References)**
QuickGraph
YAXLib

**Comment by kovacev** [comment]
what i do not understand is. for instance. here is a example of one.
EVE Killboard Analyser and Eve Local Chat Analyser both require log4net package.
NuGet downloads the package and fixes the reference in Eve Local Chat Analyser but not for EVE Killboard Analyser. ??

**Comment by rischwa** [comment]
Weird. Although it sucks, maybe try to remove the dependencies and add them back again? I don't really have a lot of other ideas tbh. You could also try removing the packages folder and see if nuget finally fixes it.

**Comment by kovacev** [comment]
i managed to fix all references/errors and got it to build.
I know that your not running RischwaNetService anymore. 
i found that KillboardAnalysisServices.cs points to RischwaNetService (http://rischwa.net/killboard/api
i want to run my own server but have no idea how your server part is setup.
did you have another repo for the server part some where ?
dannykovacev@gmail.com please let me know thanks

**Comment by rischwa** [comment]
The server is part of this repository: the "EVE Killboard Analyser" project.
Unfortunately the server setup is complex and I don't have the time to give support with it.
The only pointer I can give you is my reddit os release post: https://www.reddit.com/r/Eve/comments/6h25oe/pirates_little_helper_open_source_release/

The probably far easier solution would be to replace the server with client side killboard analysis.

**Comment by wesemann** [comment]
@kovacev what did you do to fix the dependencies?
I have problems with QuickGraph and other dependencies there are impossible to uninstall and reinstall because of a NullPointerException. The nuget recovery did not worked as well.

**Comment by rischwa** [comment]
A nullpointerexception in nuget?

**Comment by wesemann** [comment]
Yes when I try to uninstall for example Newtonsoft.Json from the GraphX.Logic subproject in order to reinstall it again, I get a System.NullReferenceException, same is with QuickGraph.
After nuget recovered the packages there are still some references missing in the GraphX.Logic and other subprojects.

**Comment by rischwa** [comment]
You could try to remove the failing dependencies manually from the .csproj file and add them again through VisualStudio afterwards.

**Comment by kovacev** [comment]
Solution.
Download fresh source
(always use the console and do this command below)
Update-Package -reinstall 
also you need to copy the StompDotNet folder in a new folder located at your 
""YOUR PROJECTS ROOT/Visual Studio 2012/Projects/StompDotNet/

This is how mine looks like (the app looks for StompDotNet.csproj in that directory
C:\Users\kovacev\source\Visual Studio 2012\Projects\StompDotNet\StompDotNet

I had to create those directories i am using VS2017.
Thats all it will work ...

**Comment by rischwa** [comment]
Awesome, thanks for the solution!
Can I close this issue now?

**Comment by kovacev** [comment]
Yep close
if he follows these steps it will work 100%
