### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by developer-will** [rischwa/eve-plh#3]
Hey, the Dscan Locator seems to hang on mine if I scan too much.
Is there a fix?

**Comment by rischwa** [comment]
Hi,

can you be a bit more specific? What do you mean with “if I scan too much”?

You are in the dscan locator and try to scan something down and after the say 8th scan step it freezes?

**Comment by developer-will** [comment]
Too many inputs in one scan (i.e. the first scan). I've also been getting lots of local scan errors.

**Comment by rischwa** [comment]
I can’t really reproduce it, could you send me a scan which fucks up PLH, please?
Local scan errors sound like ESI (CCPs API might have been down), or what kind of errors did you experience?

Just to be sure, we are talking about version 3.1.4.0 of PLH?

 

Cheers

Jonas

**Comment by developer-will** [comment]
I'm not at home until tomorrow, so I won't be able to provide any more
detail until then, but will update tomorrow.
The error was just a generic could not lookup in the title bar.

**Comment by developer-will** [comment]
Woops, I forgot about this.
Testing it again, it seems to have fixed itself and I'll go back to using it.
If it occurs again I'll reopen with example.

**Comment by rischwa** [comment]
Thx for the info!
