### ISSUE TITLE
DScan locator, scan range always 14.3AU

### ISSUE THREAD

**Issue by Azuna1** [rischwa/eve-plh#4]
so i just found this little helper and wanted to try it.
i have "all" ticked in the dscan filter
ctrl+a, ctrl +c
pling*
selecting target with doubleclick, window updates
from that step forward, every time i try to do another scan, the scan range is set to 14.3AU and the window wont update the list or do anything else

not sure what else could be relevant

**Comment by rischwa** [comment]
Have you seen https://www.youtube.com/watch?v=PitfNTCVJRA ?
I think the DScan has a new layout in game and you need to set it to km instead of AU, to be able to paste and scan km values.

**Comment by Azuna1** [comment]
My bad, missed that tiny little detail 👯‍♂️ 
works fine :)
